development:
  adapter: postgis
  encoding: unicode
  database: apapbranding_development
  pool: 5
  username: WonyoungSo
  host: localhost
  password: 
  schema_search_path: public

test:
  adapter: postgis
  encoding: unicode
  host: localhost
  database: apapbranding_test
  pool: 5
  username: WonyoungSo
  password:

production:
  adapter: postgis
  encoding: unicode
  host: localhost
  database: apapbranding_production
  pool: 5
  username: postgres
  password: apap2013
  script_dir: /usr/share/postgresql/9.1/contrib/postgis-2.0