development:
  adapter: postgresql
  encoding: unicode
  database: apapbranding_development
  pool: 5
  username: WonyoungSo
  host: localhost
  password: 
  schema_search_path: public

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: apapbranding_test
  pool: 5
  username: WonyoungSo
  password:

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: apapbranding_production
  pool: 5
  username: postgres
  password: apap2013